// Generated by build script, do not edit!
// This file is generated for the sole purpose of being included in Windows resource (.rc) files.
// DO NOT INCLUDE THIS FILE IN C++ CODE. Use #include "Runtime/Utilities/UnityConfiguration.h" instead.
#define UNITY_VERSION_BLD 1408385
#define UNITY_VERSION_UNDER_HASH "6000.0.40f1_157d81624ddf"
#define UNITY_VERSION_PARENS_HASH "6000.0.40f1 (157d81624ddf)"
#define UNITY_VERSION_WIN "6000.0.40.1408385"
